# - name: Jenkinsfile Runner Prepackaged
# You may pin to the exact commit or the version.
# uses: jenkinsci/jenkinsfile-runner-github-actions@28b21582b55af29ca1e76329b0a48aa3843c5df4
#uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
on: push
name: Jenkins file runner
jobs:
  jenkinsfile-runner-prepackaged:
    env:
      INPUT_PLUGINSTXT: '/usr/share/jenkins/ref/plugins'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # - uses: actions/setup-java@v4
    #   with:
    #     distribution: 'temurin'
    #     java-version: '8'
    #     cache: 'gradle'
    # - name: "print java info"
    #   run: env | grep JAVA_HOME
    # - name: "show java directory"
    #   run: ls -al /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.392-8/x64

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    # - name: "print github action 1"
    #   run: echo "$GITHUB_ACTION"

    # - name: "print github action 2"
    #   run: echo ${{ github.action }}

    # - name: "print plugins path 1"
    #   run: echo "$GITHUB_ACTION_PATH/plugins.txt"

    # - name: "print plugins path 2"
    #   run: echo ${{ github.action.path }}"/plugins.txt"

    # - name : Setup Jenkins
    #   uses: jenkinsci/jfr-runtime-action@master

    - uses: jenkinsci/jfr-setup-action@master
      with:
        jenkins-version: 2.387.3
        # jenkins-version: 2.361.4
        # jenkins-version: 2.346.1
        # jenkins-pm-version: 2.5.0

    - uses: jenkinsci/jfr-plugin-installation-action@master
      with:
        pluginstxt: plugins.txt
    - uses: jenkinsci/jfr-runtime-action@master
      with:
        command: run
        jenkinsfile: Jenkinsfile

    # - name: jenkinsfile-runner-prepackaged
    #   # uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
    #   uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
    #   # env:
    #   #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
